---
# Update ufw
# Steps:
# 1. Configure Firewall
# 2. show ufw status verbose

- hosts: "{{ hostname }}"
  gather_facts: "{{ debug }}"

  vars:
    # ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_pass: "{{ user_pw }}"
    ansible_become_password: "{{ user_pw }}"
    user: "{{ user }}"
    user_pw: "{{ user_pw }}"
    firewall: "{{ firewall }}"
    firewall_ssh_port: "{{ firewall_ssh_port }}"
    firewall_ssh_ips: "{{ firewall_ssh_ips }}"

  tasks:
    - name: display facts
      debug:
        var: ansible_facts
      tags: debug,never

    - name: configure Firewall
      block:
        - name: Disable IPv6
          lineinfile:
            dest: /etc/default/ufw
            regexp: '^IPV6='
            line: "IPV6=no"
            state: present

        - name: reset ufw to default
          ufw:
            state: reset

        - name: allow ssh from any ipv4
          ufw:
            rule: allow
            port: "{{ firewall_ssh_port }}"
            proto: tcp
            direction: in
            state: enabled
            log: yes
            from: "0.0.0.0/0"
            to: "0.0.0.0/0"
          when: firewall_ssh_ips == ""
        
        - name: allow ssh from specific IPs
          ufw:
            rule: allow
            port: "{{ firewall_ssh_port }}"
            proto: tcp
            direction: in
            state: enabled
            log: yes
            from_ip: "{{ item }}"
          loop: "{{ firewall_ssh_ips }}"
          when: firewall_ssh_ips != ""
      become: yes
      when: firewall

    - name: disable ufw
      ufw:
        state: disabled
      become: yes
      when: not firewall

    - name: ufw status verbose
      command: ufw status verbose
      become: yes
      register: ufw_status
  
    - name: display ufw_status
      debug:
        var: ufw_status.stdout_lines
